version: "3.8"

services:
  db:
    image: postgres:15
    container_name: wallets_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallets_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  migrations:
    build: .
    container_name: wallets_migrations
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    command: alembic upgrade head
    restart: "no"

  app:
    build: .
    container_name: wallets_app
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: .
    container_name: wallets_tests
    depends_on:
      app:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    command: pytest -v
    restart: "no"

volumes:
  pgdata:
